### ISSUE TITLE
[FORGE-1.0.3] Redstone signal opens doors regardless if locked

### ISSUE THREAD

**Issue by Pingu-Pox** [MoonflowerTeam/locksmith#16]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
1. Put down door
2. Put pressure plate in front of it
3. Step on pressure plate
4. Profit?
```

### latest.log

```shell
No crash, no log.
```

**Comment by Farcr** [comment]
Working as intended

**Comment by Pingu-Pox** [comment]
Suppose if chunk claiming is enabled this becomes a non-issue. Thanks for the quick reply!
