### ISSUE TITLE
[Feature] A keyring to hold all your keys?

### ISSUE THREAD

**Issue by Pingu-Pox** [MoonflowerTeam/locksmith#17]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
1. Make a key
2. Pair it to a lock
3. Store key on keyring (and name it outside of an anvil)
```

### latest.log

```shell
No crash, no log.
```

**Comment by Farcr** [comment]
Already in the mod, right click with a key on another key like you'd do with a bundle, or craft them together.

**Comment by Pingu-Pox** [comment]
My mind is blown, suppose this was on the modpage or something. I didn't read it :D
