### ISSUE TITLE
[Feature] Pair more than one lock to a key

### ISSUE THREAD

**Issue by Pingu-Pox** [MoonflowerTeam/locksmith#18]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
1. Make a key, pair it to a lock
2. Make another lock, pair it to the same key.

That way if your house has multiple entrances, it can be locked with one key.
```

### latest.log

```shell
No crash, no log.
```

**Comment by Farcr** [comment]
Already in the mod, just put an empty lock with an already matched key in the locksmithing table.

**Comment by Pingu-Pox** [comment]
Again, mind blown. Thanks for the help!
