### ISSUE TITLE
Missing mineable/axe tags with locksmithing table

### ISSUE THREAD

**Issue by thelegitdolt** [MoonflowerTeam/locksmith#21]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
1. first try to mine locksmithing table with axe
2 .notitcce that it is impossible
3,. ye
```

**Comment by thelegitdolt** [comment]
yo wtf

**Comment by thelegitdolt** [comment]
think you guys should add the tag, since smithing tables are made out of more iron than the locksmith tables and do have the tag

**Comment by Ocelot5836** [comment]
I made a mistake and thought this was marked for 1.16 which is EOL. I'll push a fix for it to curse.

**Comment by thelegitdolt** [comment]
oh alright, to be fair i did word the issue very poorly
