### ISSUE TITLE
Key ring disappears and duplicates keys

### ISSUE THREAD

**Issue by Aspurgus** [MoonflowerTeam/locksmith#32]
### What version are you seeing the problem on?

1.19.2

### Describe the issue

One key disappearing
1. Have an empty keyring
2. Add an assigned key to the keyring 
3. Take out the key
4. Keyring disappears

Forge 43.2.19
Locksmith 1.1.1

### latest.log

```shell
n/a, nothing shows in the log when this happens
```

**Comment by Ocelot5836** [comment]
Key rings are created by right clicking two keys on top of each other.
