### ISSUE TITLE
[Enhancement] Disable redstone for locked doors

### ISSUE THREAD

**Issue by OfficialLahusa** [MoonflowerTeam/locksmith#6]
### What version are you seeing the problem on?

1.18.x

### Describe the issue

```markdown
1. Lock a door
2. Place any redstone active component nearby
3. Activate the component
4. The door opens
```

### latest.log

```shell
not related
```

**Comment by Farcr** [comment]
Intended behavior. Placing or breaking blocks has no way to be prevented entirely to protect such locked items. This mod is not about grief prevention, but about roleplay and locking - and as such requires respect from player to player to be used properly
